api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    title: 'Api Test'
    description: 'Api tutoriel'
    version: '0.0.1'
    collection:
        pagination:
            enabled: false
            client_enabled: true
            client_items_per_page: true
            page_parameter_name: 'page'
            enabled_parameter_name: 'pagination'
            #items_per_page_parameter_name: 'itemsPerPage'
            items_per_page_parameter_name: 'count'